osrf/ros2_serial_example

src/dummy_serial.cpp
=> Change the dummy serial to match types.

include/ros2_serial_example/uart_transporter.hpp, src/dummy_serial.cpp, src/ros2_to_serial_bridge.cpp, src/uart_transporter.cpp
=> Use std::string wherever possible.

include/ros2_serial_example/transporter.hpp, src/transporter.cpp
=> Remove an unused RingBuffer method and fix some indentation.

include/ros2_serial_example/subscription_impl.hpp, src/dummy_serial.cpp, src/uart_transporter.cpp
=> Warn the user when a write failed for some reason.

include/ros2_serial_example/publisher.hpp, include/ros2_serial_example/publisher_impl.hpp, include/ros2_serial_example/subscription.hpp, include/ros2_serial_example/subscription_impl.hpp, include/ros2_serial_example/transporter.hpp, include/ros2_serial_example/uart_transporter.hpp, src/dummy_serial.cpp, src/ros2_to_serial_bridge.cpp, src/transporter.cpp, src/uart_transporter.cpp, templates/pub_sub_type.cpp.em, templates/pub_sub_type.hpp.em, templates/ros2_topics.hpp.em
=> Add in namespaces to the code.

src/uart_transporter.cpp
=> More minor fixes from clang-tidy.

src/dummy_serial.cpp, src/ros2_to_serial_bridge.cpp, src/transporter.cpp
Most of them are just latent issues, though there is a real bug in there that is fixed in 5d91e25.
=> Fix a number of issues pointed out by clang-tidy

src/transporter.cpp
1.  We weren't exiting from `find_and_copy_message` early if we didn't find the sequence.  We would eventually exit without finding what we were looking for anyway, but this should be more efficient.
1.  We had a couple of TODO's that were easy to fix, so fix them here.
=> Fix some small bugs found by code inspection.

include/ros2_serial_example/publisher.hpp, include/ros2_serial_example/publisher_impl.hpp, include/ros2_serial_example/subscription_impl.hpp, include/ros2_serial_example/transporter.hpp, include/ros2_serial_example/uart_transporter.hpp, src/dummy_serial.cpp, src/ros2_to_serial_bridge.cpp, src/transporter.cpp, src/uart_transporter.cpp, templates/ros2_topics.hpp.em
This implements https://en.wikipedia.org/wiki/Consistent_Overhead_Byte_Stuffing , which is an alternative serial protocol that is more resistant to serial problems on the wire.  It should also give a blue print on how to add new serial protocols in the future if we decide to do that.
=> Add support for alternative serial protocol COBS

include/ros2_serial_example/publisher.hpp, include/ros2_serial_example/publisher_impl.hpp, include/ros2_serial_example/ring_buffer.hpp, include/ros2_serial_example/subscription.hpp, include/ros2_serial_example/subscription_impl.hpp, include/ros2_serial_example/transporter.hpp, include/ros2_serial_example/uart_transporter.hpp, src/transporter.cpp, templates/pub_sub_type.hpp.em, templates/ros2_topics.hpp.em
=> Minor clang-tidy fixes.

include/ros2_serial_example/publisher_impl.hpp, include/ros2_serial_example/ring_buffer.hpp, include/ros2_serial_example/subscription.hpp, include/ros2_serial_example/subscription_impl.hpp, include/ros2_serial_example/transporter.hpp, include/ros2_serial_example/uart_transporter.hpp, src/ring_buffer.cpp, src/transporter.cpp, src/uart_transporter.cpp, templates/ros2_topics.hpp.em, test/test_ring_buffer.cpp
=> Switch to ROS 2 style class variable names.

CMakeLists.txt, include/ros2_serial_example/transporter.hpp, src/ros2_to_serial_bridge.cpp, src/transporter.cpp, test/test_ring_buffer.cpp, test/test_transporter.cpp
=> Add in tests for the Transporter class.

include/ros2_serial_example/transporter.hpp, src/transporter.cpp
=> Documentation for the Transporter class.

templates/pub_sub_type.cpp.em
=> Indentation fixup.

include/ros2_serial_example/publisher_impl.hpp
This makes us robust to configuration errors.
=> Handle deserialization errors.

src/transporter.cpp
=> Add in a missing return statement if our payload is way too large.

config/default_ros2_to_serial_bridge_params.yaml, src/ros2_to_serial_bridge.cpp
This just makes the YAML cleaner looking.
Fixes #55 
=> Move topics down under "topics" heading.

ros2_serial_example/CMakeLists.txt, ros2_serial_example/src/ros2_to_serial_bridge.cpp, ros2_serial_example/templates/ros2_topics.hpp.em, ros2_serial_example/test/test_ros2_topics.cpp, ros2_serial_example/test/test_transporter.cpp
This forced us to refactor ros2_topics.hpp.em a bit, but
also uncovered two bugs.
Fixes #54 
=> Add in tests for generated ros2_topics.hpp.

ros2_serial_example/src/uart_transporter.cpp
We really want to bit-level inversion, not !.
=> Fix bug in handling of UART features.

README.md, ros2_serial_example/config/default_ros2_to_serial_bridge_params.yaml
=> Add in much more detailed documentation.

README.md, ros2_serial_example/CMakeLists.txt, ros2_serial_example/config/default_ros2_to_serial_bridge_params.yaml, ros2_serial_example/include/ros2_serial_example/transporter.hpp, ros2_serial_example/include/ros2_serial_example/uart_transporter.hpp, ros2_serial_example/include/ros2_serial_example/udp_transporter.hpp, ros2_serial_example/src/dummy_serial.cpp, ros2_serial_example/src/dummy_udp.cpp, ros2_serial_example/src/ros2_to_serial_bridge.cpp, ros2_serial_example/src/transporter.cpp, ros2_serial_example/src/uart_transporter.cpp, ros2_serial_example/src/udp_transporter.cpp
This gives us another option for communications, namely, UDP sockets.
=> Add in support for the UDP backend

ros2_serial_example/include/ros2_serial_example/publisher_impl.hpp, ros2_serial_example/include/ros2_serial_example/ros2_to_serial_bridge.hpp, ros2_serial_example/include/ros2_serial_example/subscription_impl.hpp, ros2_serial_example/src/ros2_to_serial_bridge.cpp, ros2_serial_example/src/ros2_to_serial_bridge_main.cpp
The behavior of parameters changed for Dashing and newer.
=> Adding node options to allow params from command line

ros2_serial_example/src/ros2_to_serial_bridge.cpp
Fixed dynamic_serial_mapping_ms check
=> fixbug dynamic_serial_mapping_ms check

ros2_serial_example/config/px4_serial_to_ros2_bridge_params.yaml
I would like to include the PX4 parameter file as another example because interacting with PX4 it's one of the targets of this pkg
=> Adding PX4 param file
